//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccID { get; set; }
        public string username { get; set; }
        public string Pass { get; set; }
        public bool is_admin { get; set; }
    }
}
