//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public Nullable<long> Amount { get; set; }
        public Nullable<bool> Is_pay { get; set; }
        public Nullable<int> StudentID { get; set; }
        public int FeesID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
